### PR TITLE
Query Division by its Name or Alias

### PR DESCRIPTION
**Pull request by winsweet**
See more detail in README.

### CODE REVIEW

**Comment by tonyseek** [comment]
Could you introduce which situation is it used for? I have a plan to implement a traversal interface for hierarchic divisions, but never consider GB2260.py for searching by name before.

**Comment by winsweet** [comment]
Sometimes an administrative division may have more than one name in history, or other names in short.
With ``query`` method, they can be transformed into ``Division``, only one code and uniformity.
And its very useful to data-storage when I met some problems of administrative division normalization recently.

**Comment by tonyseek** [comment]
Thank you for your contribution. But in person I don't hope the fuzzy querying be a part of this library. It could be implemented in outside, by in-memory reversed mapping or integrating with specified services like ElasticSearch. The `GB2260.data.data` always be usable data source.

**Comment by winsweet** [comment]
-,- That sounds more powerful!

**Pull request closed without merging**
